In [54]:
import numpy as np
import pandas as pd

In [55]:
diamonds = pd.read_csv(r'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
# diamonds.head()

In [56]:
df = diamonds.copy()
diamonds

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [57]:
# Questions
#* basic problems
# todo 1. Read the CSV and display the first 5 and last 5 rows
# todo 2. Find the shape (rows & columns) and data types of the dataset
# todo 3. Get summary statistics for all numeric columns
# todo 4. Display unique values in the 'cut' column and count their occurrences
# todo 5. Calculate the mean price of diamonds for each cut type

In [58]:
# 1st done
# 2nd 
# print(diamonds.info())
# ! let's fix the datatypes to reduce the memory usage

# 3.5 MB => 3.2 MB => 2.3 MB 
diamonds.table = diamonds.table.astype('float16')
diamonds[['x','y','z']] = diamonds[['x','y','z']].astype('float16')
diamonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float16
 6   price    53940 non-null  int64
 7   x        53940 non-null  float16
 8   y        53940 non-null  float16
 9   z        53940 non-null  float16
dtypes: float16(4), float64(2), int64(1), object(3)
memory usage: 2.9+ MB

In [59]:
diamonds.describe()

c:\Users\HP\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
c:\Users\HP\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
c:\Users\HP\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
c:\Users\HP\anaconda3\Lib\site-packages\numpy\core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,5.394000e+04,53940.000000,5.394000e+04,5.394000e+04,5.394000e+04
mean,0.797940,61.749405,inf,3932.799722,inf,inf,inf
std,0.474011,1.432621,2.234375e+00,3989.439738,1.121094e+00,1.142578e+00,7.055664e-01
min,0.200000,43.000000,4.300000e+01,326.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.400000,61.000000,5.600000e+01,950.000000,4.710938e+00,4.718750e+00,2.910156e+00
50%,0.700000,61.800000,5.700000e+01,2401.000000,5.699219e+00,5.710938e+00,3.529297e+00
75%,1.040000,62.500000,5.900000e+01,5324.250000,6.539062e+00,6.539062e+00,4.039062e+00
max,5.010000,79.000000,9.500000e+01,18823.000000,1.074219e+01,5.890625e+01,3.179688e+01

In [60]:
print(diamonds.table.agg(['min','max']))
diamonds[['x','y','z']].agg(['min','max'])

min    43.0
max    95.0
Name: table, dtype: float16

             x         y          z
min   0.000000   0.00000   0.000000
max  10.742188  58.90625  31.796875

In [61]:
diamonds.cut.value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [62]:
diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.949219,3.980469,2.429688
1,0.21,Premium,E,SI1,59.8,61.0,326,3.890625,3.839844,2.310547
2,0.23,Good,E,VS1,56.9,65.0,327,4.050781,4.070312,2.310547
3,0.29,Premium,I,VS2,62.4,58.0,334,4.199219,4.230469,2.630859
4,0.31,Good,J,SI2,63.3,58.0,335,4.339844,4.351562,2.750000
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.750000,5.761719,3.500000
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.691406,5.750000,3.609375
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.660156,5.679688,3.560547
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.148438,6.121094,3.740234
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.828125,5.871094,3.640625

In [65]:
# diamonds = diamonds.round({
#     "carat": 2,
#     "depth": 1,
#     "table": 1,
#     "x": 2,
#     "y": 2,
#     "z": 2
# })

diamonds
diamonds.carat = diamonds.carat.round(2)
diamonds

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.949219,3.980469,2.429688
1,0.21,Premium,E,SI1,59.8,61.0,326,3.890625,3.839844,2.310547
2,0.23,Good,E,VS1,56.9,65.0,327,4.050781,4.070312,2.310547
3,0.29,Premium,I,VS2,62.4,58.0,334,4.199219,4.230469,2.630859
4,0.31,Good,J,SI2,63.3,58.0,335,4.339844,4.351562,2.750000
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.750000,5.761719,3.500000
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.691406,5.750000,3.609375
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.660156,5.679688,3.560547
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.148438,6.121094,3.740234
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.828125,5.871094,3.640625

In [67]:
df
# as you can see if we reduced the sizse using type conversion the data precision gets altered because of extra decimal places bieng added

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [68]:
diamonds.groupby(['cut','color']).price.agg(['min', 'max', 'mean', 'count'])

                 min    max         mean  count
cut       color
Fair      D      536  16386  4291.061350    163
          E      337  15584  3682.312500    224
          F      496  17995  3827.003205    312
          G      369  18574  4239.254777    314
          H      659  18565  5135.683168    303
          I      735  18242  4685.445714    175
          J      416  18531  4975.655462    119
Good      D      361  18468  3405.382175    662
          E      327  18236  3423.644159    933
          F      357  18686  3495.750275    909
          G      394  18788  4123.482204    871
          H      368  18640  4276.254986    702
          I      351  18707  5078.532567    522
          J      335  18325  4574.172638    307
Ideal     D      367  18693  2629.094566   2834
          E      326  18729  2597.550090   3903
          F      408  18780  3374.939362   3826
          G      361  18806  3720.706388   4884
          H      357  18760  3889.334831   3115
          I      348  18779  4451.970377   2093
          J      340  18508  4918.186384    896
Premium   D      367  18575  3631.292576   1603
          E      326  18477  3538.914420   2337
          F      342  18791  4324.890176   2331
          G      382  18741  4500.742134   2924
          H      368  18795  5216.706780   2360
          I      334  18823  5946.180672   1428
          J      363  18710  6294.591584    808
Very Good D      357  18542  3470.467284   1513
          E      352  18731  3214.652083   2400
          F      357  18777  3778.820240   2164
          G      354  18818  3872.753806   2299
          H      337  18803  4535.390351   1824
          I      336  18500  5255.879568   1204
          J      336  18430  5103.513274    678

In [69]:
# find mean carat rate by each clarity level
diamonds.groupby('clarity').carat.mean()

clarity
I1      1.283846
IF      0.505123
SI1     0.850482
SI2     1.077648
VS1     0.727158
VS2     0.763935
VVS1    0.503321
VVS2    0.596202
Name: carat, dtype: float64

In [78]:
df.groupby('cut').describe().loc[:,'price'][['25%','50%','75%']]

               25%     50%      75%
cut
Fair       2050.25  3282.0  5205.50
Good       1145.00  3050.5  5028.00
Ideal       878.00  1810.0  4678.50
Premium    1046.00  3185.0  6296.00
Very Good   912.00  2648.0  5372.75

In [83]:
df.sort_values(by = 'price',ascending=False).head(10)

       carat        cut color clarity  depth  table  price     x     y     z
27749   2.29    Premium     I     VS2   60.8   60.0  18823  8.50  8.47  5.16
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04
27747   1.51      Ideal     G      IF   61.7   55.0  18806  7.37  7.41  4.56
27746   2.07      Ideal     G     SI2   62.5   55.0  18804  8.20  8.13  5.11
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
27744   2.29    Premium     I     SI1   61.8   59.0  18797  8.52  8.45  5.24
27742   2.04    Premium     H     SI1   58.1   60.0  18795  8.37  8.28  4.84
27743   2.00    Premium     I     VS1   60.8   59.0  18795  8.13  8.02  4.91
27740   1.71    Premium     F     VS2   62.3   59.0  18791  7.57  7.53  4.70
27741   2.15      Ideal     G     SI2   62.6   54.0  18791  8.29  8.35  5.21

In [85]:
list = ['Premium','Ideal']
mask = df['cut'].isin(list)
df[mask]

       carat      cut color clarity  depth  table  price     x     y     z
0       0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
11      0.23    Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72    Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75    Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[35342 rows x 10 columns]

In [ ]:
df['Volume'] = df['x'] * df['y'] * df['z']

,carat,cut,color,clarity,depth,table,price,x,y,z,Volume
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,34.505856
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,38.076885
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,51.917250
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,115.920000
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,118.110175
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,114.449728
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,140.766120
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,124.568444

In [88]:
pd.crosstab(df['cut'],df['color'])

color         D     E     F     G     H     I    J
cut
Fair        163   224   312   314   303   175  119
Good        662   933   909   871   702   522  307
Ideal      2834  3903  3826  4884  3115  2093  896
Premium    1603  2337  2331  2924  2360  1428  808
Very Good  1513  2400  2164  2299  1824  1204  678