# Diamonds Dataset – Pandas Data Wrangling Practice

This notebook is designed for hands-on pandas practice using the Diamonds dataset.

In [1]:
import pandas as pd
import numpy as np

diamonds = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv")
diamonds.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

## 1. Basic Exploration
### Q1. Display the first 5 and last 5 rows of the dataset

In [4]:
# first already up there, last 5 rows are here 
diamonds.tail(5)

       carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

### Q2. Find the shape and data types of the dataset

In [8]:
print(diamonds.shape)
diamonds.dtypes
# we could do it using info() as well

(53940, 10)

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x          float64
y          float64
z          float64
dtype: object

### Q3. Get summary statistics for all numeric columns

In [43]:
diamonds.describe()
# every column except cut and color is numerical, here is the summary stats

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

### Q4. Explore the `cut` column

In [22]:
print(diamonds.cut)
print('\n===== values present in cut column=====')
diamonds['cut'].value_counts()

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: object

===== values present in cut column=====

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

### Q5. Calculate the mean price for each cut type

In [25]:
diamonds.groupby('cut').price.mean().sort_values()
# average price of diamonds for each cut category

cut
Ideal        3457.541970
Good         3928.864452
Very Good    3981.759891
Fair         4358.757764
Premium      4584.257704
Name: price, dtype: float64

## 2. Data Filtering & Selection
### Q6. Filter diamonds with carat weight ≥ 0.3

In [38]:
mask = diamonds.carat >= 0.3
diamonds[mask].sort_values('carat')
# ! if carat is same in multiple rows, then sorting is done based on index values

       carat      cut color clarity  depth  table  price      x      y     z
31991   0.30  Premium     F     VS2   62.2   60.0    776   4.27   4.22  2.64
33022   0.30    Ideal     D    VVS2   62.0   53.0    814   4.33   4.35  2.69
33023   0.30    Ideal     D    VVS2   61.9   55.0    814   4.28   4.31  2.66
33024   0.30    Ideal     D    VVS2   61.6   58.0    814   4.29   4.32  2.65
33025   0.30    Ideal     D    VVS2   61.7   55.0    814   4.33   4.36  2.68
...      ...      ...   ...     ...    ...    ...    ...    ...    ...   ...
25998   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
25999   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
27130   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
27630   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27415   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98

[52341 rows x 10 columns]

### Q7. Select diamonds with cut either Premium or Ideal

In [32]:
list = ['Premium','Ideal']
mask = diamonds['cut'].isin(list) # * it returns boolean series not a dataframe
diamonds[mask]
# filtering rows where cut is either Premium or Ideal

       carat      cut color clarity  depth  table  price     x     y     z
0       0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
11      0.23    Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72    Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75    Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[35342 rows x 10 columns]

### Q8. Select diamonds where x > 5, y > 5, and z > 5

In [49]:

# * a Quick way to mask if all the column are masked and compared with one same value
mask = diamonds[['x','y','z']] > 5


# ! diamonds[mask]
# ? this will give NaN values where condition is False, try to uncomment and run it
diamonds[mask.all(axis=1)]

       carat        cut color clarity  depth  table  price     x      y      z
11778   1.83       Fair     J      I1   70.0   58.0   5083  7.34   7.28   5.12
13002   2.14       Fair     J      I1   69.4   57.0   5405  7.74   7.70   5.36
13118   2.15       Fair     J      I1   65.5   57.0   5430  8.01   7.95   5.23
13562   1.96       Fair     F      I1   66.6   60.0   5554  7.59   7.56   5.04
13757   2.22       Fair     J      I1   66.7   56.0   5607  8.04   8.02   5.36
...      ...        ...   ...     ...    ...    ...    ...   ...    ...    ...
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90   7.97   5.04
27749   2.29    Premium     I     VS2   60.8   60.0  18823  8.50   8.47   5.16
48410   0.51  Very Good     E     VS1   61.8   54.7   1970  5.12   5.15  31.80
49189   0.51      Ideal     E     VS1   61.8   55.0   2075  5.15  31.80   5.12
49905   0.50  Very Good     G    VVS1   63.7   58.0   2180  5.01   5.04   5.06

[1457 rows x 10 columns]

### Q9. Diamonds with color D and clarity IF

In [52]:
mask = (diamonds.color == 'D') & (diamonds.clarity == 'IF')
diamonds[mask]

       carat        cut color clarity  depth  table  price     x     y     z
3342    0.50       Good     D      IF   63.2   59.0   3378  4.99  5.04  3.17
3343    0.50  Very Good     D      IF   62.9   59.0   3378  4.99  5.09  3.17
3680    0.51      Ideal     D      IF   62.0   56.0   3446  5.14  5.18  3.20
3682    0.51      Ideal     D      IF   62.1   55.0   3446  5.12  5.13  3.19
3971    0.55       Good     D      IF   58.0   62.0   3509  5.31  5.41  3.12
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
50671   0.34      Ideal     D      IF   62.1   57.0   2287  4.46  4.52  2.79
50672   0.34      Ideal     D      IF   59.8   57.0   2287  4.57  4.59  2.74
51173   0.34      Ideal     D      IF   62.1   57.0   2346  4.52  4.46  2.79
51174   0.34      Ideal     D      IF   59.8   57.0   2346  4.59  4.57  2.74
53456   0.48  Very Good     D      IF   60.6   55.0   2677  5.08  5.12  3.09

[73 rows x 10 columns]

### Q10. Top 10 most expensive diamonds

In [53]:
diamonds.sort_values('price', ascending=False).head(10)

       carat        cut color clarity  depth  table  price     x     y     z
27749   2.29    Premium     I     VS2   60.8   60.0  18823  8.50  8.47  5.16
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04
27747   1.51      Ideal     G      IF   61.7   55.0  18806  7.37  7.41  4.56
27746   2.07      Ideal     G     SI2   62.5   55.0  18804  8.20  8.13  5.11
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
27744   2.29    Premium     I     SI1   61.8   59.0  18797  8.52  8.45  5.24
27742   2.04    Premium     H     SI1   58.1   60.0  18795  8.37  8.28  4.84
27743   2.00    Premium     I     VS1   60.8   59.0  18795  8.13  8.02  4.91
27740   1.71    Premium     F     VS2   62.3   59.0  18791  7.57  7.53  4.70
27741   2.15      Ideal     G     SI2   62.6   54.0  18791  8.29  8.35  5.21

## 3. Data Manipulation
### Q11. Create a new column 'volume' = x * y * z for each diamond

In [56]:
diamonds['volume'] = diamonds['x'] * diamonds['y'] * diamonds['z']
diamonds.head()
# ? 1. here we can't create a volume column using diamonds.volume
# ? 2. we don't need to create a function and use apply here as pandas does it vectorized way

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,34.505856
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,38.076885
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,51.917250

### Q12. Add a price_per_carat column (price / carat)

In [61]:
diamonds['price_per_carat'] = diamonds['price'] / diamonds['carat']
diamonds.sort_values('price_per_carat', ascending=False).head(10)

,carat,cut,color,clarity,depth,table,price,x,y,z,volume,price_per_carat
27635,1.04,Very Good,D,IF,61.3,56.0,18542,6.53,6.55,4.01,171.513715,17828.846154
27530,1.07,Premium,D,IF,60.9,58.0,18279,6.67,6.57,4.03,176.602257,17083.177570
27226,1.03,Ideal,D,IF,62.0,56.0,17590,6.55,6.44,4.03,169.993460,17077.669903
27457,1.07,Very Good,D,IF,60.9,58.0,18114,6.57,6.67,4.03,176.602257,16928.971963
26998,1.02,Very Good,D,IF,61.7,59.0,17100,6.42,6.52,3.99,167.015016,16764.705882
27349,1.07,Very Good,D,IF,59.0,59.0,17909,6.63,6.72,3.94,175.541184,16737.383178
27507,1.09,Very Good,D,IF,61.7,58.0,18231,6.55,6.65,4.07,177.279025,16725.688073
26660,1.00,Ideal,D,IF,60.7,57.0,16469,6.44,6.48,3.92,163.586304,16469.000000
26549,1.01,Premium,D,IF,61.6,56.0,16234,6.46,6.43,3.97,164.905066,16073.267327
26483,1.00,Very Good,D,IF,63.3,59.0,16073,6.37,6.33,4.02,162.094842,16073.000000

> here is the findings related to dataset :-
if you look at the color column, you'll realise that all "D" coloured diamonds have the highest
<br> -> price/carat value

but the the D is not the most expensive diamond in terms of prices

In [65]:

# ! here you see 
diamonds.groupby('color').price.mean().sort_values()
# average price of diamonds for each color category

color
E    3076.752475
D    3169.954096
F    3724.886397
G    3999.135671
H    4486.669196
I    5091.874954
J    5323.818020
Name: price, dtype: float64

### Q13. Rename columns: 'x' → 'length', 'y' → 'width', 'z' → 'depth'

In [68]:
diamonds.rename(columns={'x': 'length','y': 'width', 'z': 'depth'}, inplace=True)
diamonds.head()

,carat,cut,color,clarity,depth,table,price,length,width,depth,volume,price_per_carat
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,38.202030,1417.391304
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,34.505856,1552.380952
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,38.076885,1421.739130
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,46.724580,1151.724138
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,51.917250,1080.645161

### Q14. Sort the dataframe by price in descending order

---
### Checking if the column is sorted in original dataset
> in order to do this we run a loop in the column of Dataframe itself

In [79]:
for i in range(len(diamonds) - 1):
    if diamonds.iloc[i].price > diamonds.iloc[i+1].price:
        print(f"Not sorted at row {i} → {i+1}")
        break
        
else:
    print("Price column is sorted in ascending order")

Not sorted at row 389 → 390

---

### Q15. Remove depth and table columns

In [80]:
diamonds.drop(columns= ['depth','table'])

,carat,cut,color,clarity,price,length,width,volume,price_per_carat
0,0.23,Ideal,E,SI2,326,3.95,3.98,38.202030,1417.391304
1,0.21,Premium,E,SI1,326,3.89,3.84,34.505856,1552.380952
2,0.23,Good,E,VS1,327,4.05,4.07,38.076885,1421.739130
3,0.29,Premium,I,VS2,334,4.20,4.23,46.724580,1151.724138
4,0.31,Good,J,SI2,335,4.34,4.35,51.917250,1080.645161
...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,2757,5.75,5.76,115.920000,3829.166667
53936,0.72,Good,D,SI1,2757,5.69,5.75,118.110175,3829.166667
53937,0.70,Very Good,D,SI1,2757,5.66,5.68,114.449728,3938.571429
53938,0.86,Premium,H,SI2,2757,6.15,6.12,140.766120,3205.813953
53939,0.75,Ideal,D,SI2,2757,5.83,5.87,124.568444,3676.000000

## 4. Aggregation & Grouping
### Q16. Calculate count, min, max, and mean price for each cut

In [82]:
diamonds.groupby('cut').price.agg(['count','mean','min','max'])

           count         mean  min    max
cut
Fair        1610  4358.757764  337  18574
Good        4906  3928.864452  327  18788
Ideal      21551  3457.541970  326  18806
Premium    13791  4584.257704  326  18823
Very Good  12082  3981.759891  336  18818

### Q17. Average price grouped by cut and color

In [85]:
diamonds.groupby(['cut','color']).price.mean()

cut        color
Fair       D        4291.061350
           E        3682.312500
           F        3827.003205
           G        4239.254777
           H        5135.683168
           I        4685.445714
           J        4975.655462
Good       D        3405.382175
           E        3423.644159
           F        3495.750275
           G        4123.482204
           H        4276.254986
           I        5078.532567
           J        4574.172638
Ideal      D        2629.094566
           E        2597.550090
           F        3374.939362
           G        3720.706388
           H        3889.334831
           I        4451.970377
           J        4918.186384
Premium    D        3631.292576
           E        3538.914420
           F        4324.890176
           G        4500.742134
           H        5216.706780
           I        5946.180672
           J        6294.591584
Very Good  D        3470.467284
           E        3214.652083
           F        3778.820240
           G        3872.753806
           H        4535.390351
           I        5255.879568
           J        5103.513274
Name: price, dtype: float64

### Q18. Mean carat weight for each clarity level

In [86]:
diamonds.groupby('clarity').carat.mean()

clarity
I1      1.283846
IF      0.505123
SI1     0.850482
SI2     1.077648
VS1     0.727158
VS2     0.763935
VVS1    0.503321
VVS2    0.596202
Name: carat, dtype: float64

### Q19. Cross-tabulation between cut and color

In [87]:
pd.crosstab(diamonds.cut, diamonds.color)

color         D     E     F     G     H     I    J
cut
Fair        163   224   312   314   303   175  119
Good        662   933   909   871   702   522  307
Ideal      2834  3903  3826  4884  3115  2093  896
Premium    1603  2337  2331  2924  2360  1428  808
Very Good  1513  2400  2164  2299  1824  1204  678

### Q20. Cut-clarity combination with highest average price

In [96]:
diamonds.groupby(['cut','clarity']).price.mean().sort_values(ascending=False).head(19)

cut        clarity
Premium    SI2        5545.936928
Fair       SI2        5173.916309
Very Good  SI2        4988.688095
Ideal      SI2        4755.952656
Good       SI2        4580.260870
Premium    VS2        4550.331248
           VS1        4485.462041
           SI1        4455.269371
Very Good  IF         4396.216418
Ideal      I1         4335.726027
Good       VS2        4262.236196
Very Good  VS2        4215.759552
Fair       SI1        4208.279412
           VS2        4174.724138
           VS1        4165.141176
Good       IF         4098.323944
Very Good  I1         4078.226190
Premium    I1         3947.331707
Very Good  SI1        3932.391049
Name: price, dtype: float64

## 5. Missing Values & Data Cleaning
### Q21. Check for missing values

In [100]:
print(diamonds.isna().sum())
diamonds.isnull().sum()

carat              0
cut                0
color              0
clarity            0
depth              0
table              0
price              0
length             0
width              0
depth              0
volume             0
price_per_carat    0
dtype: int64

carat              0
cut                0
color              0
clarity            0
depth              0
table              0
price              0
length             0
width              0
depth              0
volume             0
price_per_carat    0
dtype: int64

### Q22. Boolean dataframe showing missing values

In [103]:
diamonds.isna()

,carat,cut,color,clarity,depth,table,price,length,width,depth,volume,price_per_carat
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,False,False,False,False,False,False,False,False,False,False,False,False
53936,False,False,False,False,False,False,False,False,False,False,False,False
53937,False,False,False,False,False,False,False,False,False,False,False,False
53938,False,False,False,False,False,False,False,False,False,False,False,False
53939,False,False,False,False,False,False,False,False,False,False,False,False

In [102]:
diamonds.isnull()

,carat,cut,color,clarity,depth,table,price,length,width,depth,volume,price_per_carat
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,False,False,False,False,False,False,False,False,False,False,False,False
53936,False,False,False,False,False,False,False,False,False,False,False,False
53937,False,False,False,False,False,False,False,False,False,False,False,False
53938,False,False,False,False,False,False,False,False,False,False,False,False
53939,False,False,False,False,False,False,False,False,False,False,False,False

### Q23. Drop rows with any missing values

In [105]:
diamonds.dropna()
#thier are no missing values in this dataset

,carat,cut,color,clarity,depth,table,price,length,width,depth,volume,price_per_carat
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,38.202030,1417.391304
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,34.505856,1552.380952
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,38.076885,1421.739130
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,46.724580,1151.724138
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,51.917250,1080.645161
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,115.920000,3829.166667
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,118.110175,3829.166667
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,114.449728,3938.571429
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,140.766120,3205.813953
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,124.568444,3676.000000

### Q24. Fill missing numeric values with the mean

In [109]:
diamonds.fillna('unknown')

,carat,cut,color,clarity,depth,table,price,length,width,depth,volume,price_per_carat
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,38.202030,1417.391304
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,34.505856,1552.380952
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,38.076885,1421.739130
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,46.724580,1151.724138
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,51.917250,1080.645161
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,115.920000,3829.166667
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,118.110175,3829.166667
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,114.449728,3938.571429
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,140.766120,3205.813953
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,124.568444,3676.000000

## 6. Advanced Operations
### Q25. Calculate percentile (25th, 50th, 75th) of price by cut type

In [116]:
# there are two ways to get the same percentile values
print(diamonds['price'].quantile([0.25,0.5,0.75]))

diamonds['price'].describe()[['25%','50%','75%']]

0.25     950.00
0.50    2401.00
0.75    5324.25
Name: price, dtype: float64

25%     950.00
50%    2401.00
75%    5324.25
Name: price, dtype: float64

### Q26. Diamonds in the top 5% by price

In [117]:
diamonds.price.quantile(0.05)

544.0

### Q27. Categorize diamonds based on price

Tasks:
- Create a new column `price_category`:
  - `budget` : price in [0, 1000)
  - `mid-range` : [1000, 5000)
  - `premium` : [5000, 10000)
  - `luxury` : [10000, ∞)
- Count how many diamonds fall in each category.

In [130]:

# ! i don't know this method yet but the work is same as we do in other approach
# diamonds['Price Category'] = pd.cut(diamonds['price'], bins=[0,500,1500,3000,10000], labels=['Low','Medium','High','Very High'])
# diamonds['Price Category']

def categorize(col):
    if col < 1000:
        return 'Budget'
    elif 1000 <= col < 5000:
        return 'Mid-Range'
    elif 5000 <= col < 10000:
        return 'Premium'
    else:
        return 'Luxury'

diamonds['Price_Category'] = diamonds['price'].apply(categorize)

In [135]:

# * additional stuff

# diamonds.drop(columns='Price Category', inplace=True)
diamonds.Price_Category.value_counts()

Price_Category
Mid-Range    24714
Budget       14499
Premium       9504
Luxury        5223
Name: count, dtype: int64

### Q28. Create a quality_score using apply
> Use .apply() to create a quality_score = (carat * 2) + price_per_carat

In [136]:

# ? i already shown the implementation of apply above so i won't solve it again here 😤😤

### Q29. Variance in price by cut
> Group by cut and find the variance in price for each group

In [137]:
diamonds.groupby('cut').price.var()

cut
Fair         1.267635e+07
Good         1.355410e+07
Ideal        1.450392e+07
Premium      1.891558e+07
Very Good    1.549101e+07
Name: price, dtype: float64

### Q30. Random sample of 1000 diamonds
> Create a sample of 1000 random diamonds and calculate stats on the sample

In [138]:
diamonds.sample(1000).describe()

,carat,depth,table,price,length,width,depth,volume,price_per_carat
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.804800,61.716800,57.507100,3974.324000,5.745050,5.749730,3.541610,130.474896,3997.954194
std,0.479028,1.323658,2.287346,4039.191616,1.127148,1.117831,0.702157,76.769005,2002.207015
min,0.230000,56.300000,53.000000,336.000000,3.940000,3.970000,0.000000,0.000000,1109.090909
25%,0.400000,61.100000,56.000000,942.000000,4.730000,4.740000,2.910000,65.551718,2474.583333
50%,0.700000,61.900000,57.000000,2465.500000,5.700000,5.720000,3.530000,114.792585,3530.851648
75%,1.050000,62.500000,59.000000,5339.000000,6.570000,6.570000,4.040000,172.168111,4928.088235
max,3.000000,67.500000,68.000000,18787.000000,9.320000,9.190000,5.500000,471.079400,12609.243697

In [140]:

# ! as you can see below the description of entire dataframe and of 1000 samples is quite different.
# todo that's the reason why initially the model doesn't get right predictions, because the sample taken for training might not represent the entire data well enough.
diamonds.describe()

,carat,depth,table,price,length,width,depth,volume,price_per_carat
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734,129.849403,4008.394796
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699,78.245262,2012.665747
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000,0.000000,1051.162791
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000,65.136830,2477.944444
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000,114.808572,3495.198031
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000,170.842451,4949.599702
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000,3840.598060,17828.846154