In [12]:
import numpy as np
import pandas as pd

In [13]:
ipl = pd.read_csv(r"C:\Users\HP\Downloads\deliveries.csv")
movies = pd.read_csv(r"C:\Users\HP\Downloads\imdb-top-1000.csv")

In [14]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [15]:
genres = movies.groupby("Genre")
genres.apply(lambda x : x)
# genres

C:\Users\HP\AppData\Local\Temp\ipykernel_20780\3265664615.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(lambda x : x)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

[1000 rows x 10 columns]

In [16]:
# genres.size()
some = movies.Genre.groupby(movies['Released_Year']).apply(lambda x: x).value_counts()
# type(some)
some

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [17]:
# let's use some methods on groupby object
genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [18]:
genres.get_group('Action')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
979,Lethal Weapon,1987,109,Action,7.6,Richard Donner,Mel Gibson,236894,65207127.0,68.0
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
983,The Warriors,1979,92,Action,7.6,Walter Hill,Michael Beck,93878,22490039.0,65.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0

In [19]:
genres['IMDB_Rating'].agg(['mean', 'max', 'min'])

               mean  max  min
Genre
Action     7.949419  9.0  7.6
Adventure  7.937500  8.6  7.6
Animation  7.930488  8.6  7.6
Biography  7.938636  8.9  7.6
Comedy     7.901290  8.6  7.6
Crime      8.016822  9.2  7.6
Drama      7.957439  9.3  7.6
Family     7.800000  7.8  7.8
Fantasy    8.000000  8.1  7.9
Film-Noir  7.966667  8.1  7.8
Horror     7.909091  8.5  7.6
Mystery    7.975000  8.4  7.6
Thriller   7.800000  7.8  7.8
Western    8.350000  8.8  7.8

In [20]:
genres.agg({'IMDB_Rating' : ['mean', 'max', 'min'], 'Released_Year' : ['first', 'last', 'nunique']})

          IMDB_Rating           Released_Year
                 mean  max  min         first  last nunique
Genre
Action       7.949419  9.0  7.6          2008  1979      61
Adventure    7.937500  8.6  7.6          2014  1970      49
Animation    7.930488  8.6  7.6          2001  1967      35
Biography    7.938636  8.9  7.6          1993  1978      44
Comedy       7.901290  8.6  7.6          2019  1961      72
Crime        8.016822  9.2  7.6          1972  1935      56
Drama        7.957439  9.3  7.6          1994  1944      83
Family       7.800000  7.8  7.8          1982  1971       2
Fantasy      8.000000  8.1  7.9          1920  1922       2
Film-Noir    7.966667  8.1  7.8          1949  1943       3
Horror       7.909091  8.5  7.6          1960  2001      11
Mystery      7.975000  8.4  7.6          2000  1997      11
Thriller     7.800000  7.8  7.8          1967  1967       1
Western      8.350000  8.8  7.8          1966  1976       4

In [21]:
genres.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [32]:
genres['Gross'].sum().sort_values(ascending=False)

Genre
Drama        3.540997e+10
Action       3.263226e+10
Comedy       1.566387e+10
Animation    1.463147e+10
Adventure    9.496922e+09
Crime        8.452632e+09
Biography    8.276358e+09
Mystery      1.256417e+09
Horror       1.034649e+09
Fantasy      7.827267e+08
Family       4.391106e+08
Film-Noir    1.259105e+08
Western      5.822151e+07
Thriller     1.755074e+07
Name: Gross, dtype: float64

In [46]:
# movies['Gross'].sum()
df = pd.read_csv(r"C:\Users\HP\Downloads\indian_cities_full_150.csv")
df.population.sum()  # 125635140

125635140

In [45]:
print(df[df.city_tier == "Tier-1"].population.sum())
print(df[df.city_tier == "Tier-2"].population.sum())
print(df[df.city_tier == "Tier-3"].population.sum())
# 125635140

66492550
43244700
15897890

In [55]:
df.groupby('city_tier').population.sum()  # 125635140
df_tiers = df.groupby('city_tier')

In [87]:
# df_tiers.agg([sum,min,max])
idx = df_tiers.population.idxmax()
df.iloc[idx]

   city_name city_tier  population
0     Mumbai    Tier-1    12442373
10   Lucknow    Tier-2     3382000
40    Mysuru    Tier-3      920550

In [112]:
genres.agg('mean', numeric_only=True)
genres.mean(numeric_only=True)
genres.agg(['mean', 'max', 'min', ], numeric_only=True)

               Runtime  IMDB_Rating   No_of_Votes         Gross   Metascore
Genre
Action      812.290222     0.092573  1.874429e+11  5.092802e+16  154.287501
Adventure  1110.043818     0.052799  9.071442e+10  2.881653e+16  152.408730
Animation   211.134598     0.064121  6.873480e+10  4.375794e+16   77.680360
Biography   650.987983     0.071364  7.359511e+10  1.858452e+16  121.620902
Comedy      526.528697     0.052336  3.559017e+10  3.788913e+16  139.929032
Crime       766.693528     0.112545  1.398758e+11  2.468643e+16  171.586474
Drama       769.534770     0.071411  9.336335e+10  4.845123e+16  162.427040
Family      112.500000     0.000000  1.877128e+10  9.292815e+16  288.000000
Fantasy     162.000000     0.020000  4.919130e+08  5.786433e+15         NaN
Film-Noir    16.000000     0.023333  2.986522e+09  4.968096e+15    2.333333
Horror      185.090909     0.096909  5.517026e+10  9.930155e+15  236.000000
Mystery     209.537879     0.096591  1.637189e+11  2.457132e+16  346.125000
Thriller           NaN          NaN           NaN           NaN         NaN
Western     294.250000     0.176667  6.942675e+10  1.514441e+14   81.583333

In [108]:
movies.groupby([ 'Director', 'Star1']).Gross.sum().sort_values(ascending=False)

Director              Star1
Akira Kurosawa        Toshirô Mifune     2.999877e+09
Anthony Russo         Joe Russo          2.205039e+09
Billy Wilder          William Holden     1.286779e+09
Christopher Nolan     Christian Bale     1.242940e+09
Werner Herzog         Klaus Kinski       1.124605e+09
                                             ...
Jeong-beom Lee        Won Bin            6.460000e+03
Shane Meadows         Paddy Considine    6.013000e+03
Jaco Van Dormael      Jared Leto         3.600000e+03
Thomas Jahn           Til Schweiger      3.296000e+03
Anders Thomas Jensen  Ulrich Thomsen     1.305000e+03
Name: Gross, Length: 898, dtype: float64

In [99]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [120]:
# help(pd.DataFrame.groupby)
genres.groups
genres.get_group('Action')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
979,Lethal Weapon,1987,109,Action,7.6,Richard Donner,Mel Gibson,236894,65207127.0,68.0
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
983,The Warriors,1979,92,Action,7.6,Walter Hill,Michael Beck,93878,22490039.0,65.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0

In [121]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [ ]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [133]:
genres.Runtime.describe()

           count        mean        std    min     25%    50%     75%    max
Genre
Action     172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure   72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation   82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography   88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy     155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime      107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama      289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family       2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy      2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir    3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror      11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery     12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller     1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western      4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

In [137]:
genres.sample(2, replace=True )

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
351,Yip Man,2008,106,Action,8.0,Wilson Yip,Donnie Yen,211427,613703997.0,59.0
850,Enter the Dragon,1973,102,Action,7.7,Robert Clouse,Bruce Lee,96561,25000000.0,83.0
692,The Man Who Would Be King,1975,129,Adventure,7.8,John Huston,Sean Connery,44917,335861628.0,91.0
323,Togo,2019,113,Adventure,8.0,Ericson Core,Willem Dafoe,37556,874211619.0,69.0
229,Mary and Max,2009,92,Animation,8.1,Adam Elliot,Toni Collette,164462,873839108.0,NaN
596,Toy Story 4,2019,100,Animation,7.8,Josh Cooley,Tom Hanks,203177,434038008.0,84.0
346,The King's Speech,2010,118,Biography,8.0,Tom Hooper,Colin Firth,639603,138797449.0,88.0
139,Bhaag Milkha Bhaag,2013,186,Biography,8.2,Rakeysh Omprakash Mehra,Farhan Akhtar,61137,1626289.0,NaN
973,Home Alone,1990,103,Comedy,7.6,Chris Columbus,Macaulay Culkin,488817,285761243.0,63.0
565,A Night at the Opera,1935,96,Comedy,7.9,Sam Wood,Edmund Goulding,30580,2537520.0,NaN
163,Eskiya,1996,128,Crime,8.2,Yavuz Turgul,Sener Sen,64118,764480450.0,NaN
795,Ocean's Eleven,2001,116,Crime,7.7,Steven Soderbergh,George Clooney,516372,183417150.0,74.0
268,Platoon,1986,120,Drama,8.1,Oliver Stone,Charlie Sheen,381222,138530565.0,92.0
302,Le notti di Cabiria,1957,110,Drama,8.1,Federico Fellini,Giulietta Masina,42940,752045.0,NaN
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
829,Spoorloos,1988,107,Mystery,7.7,George Sluizer,Bernard-Pierre Donnadieu,33982,367916835.0,NaN
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

In [140]:
genres.agg({'Runtime' :'mean', 'IMDB_Rating' : 'mean', 'No_of_Votes' : 'sum', 'Gross':'sum','Metascore':'mean'})

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10  73.419580
Adventure  134.111111     7.937500     22576163  9.496922e+09  78.437500
Animation   99.585366     7.930488     21978630  1.463147e+10  81.093333
Biography  136.022727     7.938636     24006844  8.276358e+09  76.240506
Comedy     112.129032     7.901290     27620327  1.566387e+10  78.720000
Crime      126.392523     8.016822     33533615  8.452632e+09  77.080460
Drama      124.737024     7.957439     61367304  3.540997e+10  79.701245
Family     107.500000     7.800000       551221  4.391106e+08  79.000000
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08  95.666667
Horror     102.090909     7.909091      3742556  1.034649e+09  80.000000
Mystery    119.083333     7.975000      4203004  1.256417e+09  79.125000
Thriller   108.000000     7.800000        27733  1.755074e+07  81.000000
Western    148.250000     8.350000      1289665  5.822151e+07  78.250000

In [148]:
idx = []

for grp,data in genres:
    # print(data['Runtime'].sum() / data.count())
    idx.append(data['IMDB_Rating'].idxmax())

movies.iloc[idx]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [169]:
# framo = pd.DataFrame()

def ranking(data):
    data['IMDB_rank'] = data['IMDB_Rating'].rank(ascending=False)
    return data.sort_values('IMDB_Rating',ascending=False)

framo = genres.apply(ranking)
framo.loc['Action']
# framo
# genres.count()

C:\Users\HP\AppData\Local\Temp\ipykernel_20780\684767915.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  framo = genres.apply(ranking)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,IMDB_rank
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0,2.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0,3.5
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0,3.5
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...
893,Sicario,2015,121,Action,7.6,Denis Villeneuve,Emily Blunt,371291,46889293.0,82.0,160.0
889,Only the Brave,2017,134,Action,7.6,Joseph Kosinski,Josh Brolin,58371,18340051.0,72.0,160.0
888,Baby Driver,2017,113,Action,7.6,Edgar Wright,Ansel Elgort,439406,107825862.0,86.0,160.0
887,Guardians of the Galaxy Vol. 2,2017,136,Action,7.6,James Gunn,Chris Pratt,569974,389813101.0,67.0,160.0
985,Escape from Alcatraz,1979,112,Action,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0,160.0

In [158]:
movies['IMDB_Rating'].sort_values(ascending=False)

0      9.3
1      9.2
2      9.0
3      9.0
4      9.0
      ...
912    7.6
911    7.6
910    7.6
909    7.6
999    7.6
Name: IMDB_Rating, Length: 1000, dtype: float64

In [193]:
idx = genres['IMDB_Rating'].idxmax()
movies.loc[idx]
# movies[movies['Genre'] == 'Adventure'].sort_values('Series_Title', ascending=False).max()
# movies.iloc[i]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [196]:
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64

In [198]:
def start_A(grp) :
    mask = grp['Series_Title'].str.startswith('A')
    return grp[mask]


genres.apply(start_A)

C:\Users\HP\AppData\Local\Temp\ipykernel_20780\3818469201.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(start_A)

                      Series_Title Released_Year  Runtime   Genre  \
Genre
Action 59        Avengers: Endgame          2019      181  Action
       60   Avengers: Infinity War          2018      149  Action
       106                  Aliens          1986      137  Action
       166         Andaz Apna Apna          1994      160  Action
       224             A Wednesday          2008      104  Action
...                            ...           ...      ...     ...
Drama  804           Abre los ojos          1997      119   Drama
       813       A Little Princess          1995       97   Drama
       824          A Few Good Men          1992      138   Drama
       903          A Star Is Born          2018      136   Drama
Horror 75                    Alien          1979      117  Horror

            IMDB_Rating            Director             Star1  No_of_Votes  \
Genre
Action 59           8.4       Anthony Russo         Joe Russo       809955
       60           8.4       Anthony Russo         Joe Russo       834477
       106          8.3       James Cameron  Sigourney Weaver       652719
       166          8.2   Rajkumar Santoshi        Aamir Khan        49300
       224          8.1       Neeraj Pandey       Anupam Kher        73891
...                 ...                 ...               ...          ...
Drama  804          7.7  Alejandro Amenábar   Eduardo Noriega        64082
       813          7.7      Alfonso Cuarón   Liesel Matthews        32236
       824          7.7          Rob Reiner        Tom Cruise       235388
       903          7.6      Bradley Cooper         Lady Gaga       334312
Horror 75           8.4        Ridley Scott  Sigourney Weaver       787806

                  Gross  Metascore
Genre
Action 59   858373000.0       78.0
       60   678815482.0       68.0
       106   85160248.0       84.0
       166  213351844.0        NaN
       224  573329738.0        NaN
...                 ...        ...
Drama  804     368234.0        NaN
       813   10019307.0       83.0
       824  141340178.0       62.0
       903  215288866.0       88.0
Horror 75    78900000.0       89.0

[63 rows x 10 columns]

In [203]:
def rank_laga(grp):
    grp['Imdb rank'] = grp['IMDB_Rating'].rank(ascending=False)
    return grp.sort_values('IMDB_Rating', ascending=False)

# genres.apply(lambda x: x)
genres.apply(rank_laga)

C:\Users\HP\AppData\Local\Temp\ipykernel_20780\2487055141.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(rank_laga)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              Imdb rank
Genre
Action   2          1.0
         5          2.0
         8          3.5
         10         3.5
         13         6.0
...                 ...
Thriller 700        1.0
Western  12         1.0
         48         2.0
         115        3.0
         691        4.0

[1000 rows x 11 columns]

In [216]:
temp = ipl[ipl['over'] >15]
mask_in_temp = temp['batsman_runs'].isin([4,6])


# temp[mask_in_temp]['batsman'].value_counts()

temp[mask_in_temp]['batsman'].groupby(temp['batsman']).count().sort_values(ascending=False)

batsman
MS Dhoni          340
AB de Villiers    208
RG Sharma         208
KA Pollard        206
V Kohli           160
                 ...
KC Cariappa         1
Shivam Sharma       1
Shoaib Malik        1
T Curran            1
KJ Abbott           1
Name: batsman, Length: 360, dtype: int64